### ISSUE TITLE
Doom integration? Daemon advantages?

### ISSUE THREAD

**Issue by cobblepot1** [jfhbrook/Cackledaemon#18]
Sorry in advance for the ignorant question. I am brand new to Emacs and have Doom Emacs up and running on Win 10 after many setbacks. I'm trying to write documentation to help other total newbies (including older people coming from MS Office) get emacs up and running. 

I cannot tell how Cackledaemon fits into that goal. Was this written to solve a particular problem with Emacs on Windows, or more as an exercise? I read the article that says "I wanted to use the Emacs daemon because any non-trivial configuration, like Doom, takes a while to load. The same way that you don't want to use CGI to handle web requests, you don't want to load Emacs every time you want to edit a file either." My Doom config loads with all modules in 4 seconds - is that unusual?

You also wrote, "But I also wanted to be able to interact with it using a nice interface. Between wanting a nice way to manage the Emacs daemon and wanting tools to manage installing and updating Emacs, writing a module seemed like a natural thing to do."

Does installing Cackledaemon also set up Doom Emacs, or just vanilla Emacs? How does running Emacs in a daemon differ from running Doom Emacs for Windows in a standard way (i.e. not in WSL) ? Is it easier to install? Does it avoid problems? Why go one way or the other?

Information on this is very appreciated!

**Comment by jfhbrook** [comment]
> Was this written to solve a particular problem with Emacs on Windows, or more as an exercise?

C'mon man,  I spent like six hard full time weeks on this. An exercise? Christ. All I can say here is that I describe the issues I'm solving in excruciating detail in the documentation, If those don't speak to you, fine.

>  My Doom config loads with all modules in 4 seconds - is that unusual?

Four seconds is, to me, a long time, but I also have a lot of the plugins enabled. Maybe you have fewer of them? Doom specifically is also highly speed-optimized -- other distributions, such as spacemacs, are not.

> Does installing Cackledaemon also set up Doom Emacs, or just vanilla Emacs? 

It sets up vanilla Emacs. I coincidentally use Doom, and the name of the project is (mostly) coincidentally Doom-the-video-game adjacent but is actually a Homestar Runner reference. I apologize for any confusion.

> How does running Emacs in a daemon differ from running Doom Emacs for Windows in a standard way (i.e. not in WSL) ? Is it easier to install? Does it avoid problems? Why go one way or the other?

The install process *is* the standard way - running a daemon just means running a headless Emacs as a background process and then having `emacsclient` connect to it over a socket. As far as what problems that avoids, I discussed that in the documentation that you already read and apparently didn't find compelling. If you have more questions about running Emacs as a daemon, I'd encourage you to read [the wiki page on it](https://www.emacswiki.org/emacs/EmacsAsDaemon) as well as the [official documentation](https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html).

**Comment by jfhbrook** [comment]
I apologize if this comes off as snippy. You may appreciate [this blog post](https://dev.to/jfhbrook/introducing-cackledaemon-2dek) which includes some screenshots.

**Comment by quickfold** [comment]
Hi Josh, thanks for your response, and no worries about coming off as snippy. Just for context, I'm an old Prof. Grandpa who is trying to learn about Emacs with the end goal of creating instructions for setting up org-mode with org-roam and other packages, ultimately to allow people to take linked notes and write academic texts with full citations and output to MS Word. Word is required for many of us to submit to journals. I've used MS Office for decades and am only 2 weeks into the Emacs process, so apologies for my ignorant questions. 

I did read the blog post you linked and the docs. I know you spent a long time on this project, so I asked my questions in part because you obviously thought it was very beneficial, and I did not understand the benefit. I didn't mean to disparage the project or suggest that it was not a good use of time. The main benefits of Crackledaemon seem to be 1) simplifying installation of Emacs on Win, 2) reducing load time when you want to use Emacs to edit a file, and 3) the tray icon that lets you perform maintenance functions on Emacs. Let me know if I missed something.

I read the wiki and manual you linked to. Am I correct that running Emacs as a daemon will allow me to assign Emacs as a default program in Win for e.g. `.org` files and have them open in the current running instance of Emacs?

I wrote primarily because I am trying to figure out a simple installation process to recommend for Doom Emacs and Cackledaemon seemed perfect. If it doesn't install Doom Emacs, is it compatible with Doom Emacs? Can I run it, install Doom on top of it, and update Cackledaemon and Doom each separately without problems or will they conflict?

Lastly, if I already have Doom Emacs installed for Win in the regular way, can I install Cackledaemon without uninstalling Doom and/or Emacs? Or would I have to uninstall first?

Thanks for your help.

**Comment by jfhbrook** [comment]
Hey, my apologies, I was having a bad day and misread your messages as shitposting.

One thing that I think is not great about Emacs is that it's written and architected in a way that makes a lot of sense to an old lispy unix hacker but is borderline hostile towards normal users. I wrote about how running Emacs on Windows is hard mode because of the unix-y assumptions Emacs makes, and you and me both know from experience that the unix-y assumptions the Doom project makes additionally make it a huge pain in the ass to set up.

Beyond that, though, I think the Emacs stack really assumes that the person using it is a programmer that's comfortable with build systems, version control, client-server architectures, launching things from the command line and so on. I definitely made that assumption when working on this project. It sounds like these assumptions might be a stretch for your target audience - that's fine, I just wasn't counting on it.

So this project kinda does a few things, and I'll try to touch on them separately.

The first is that, yeah, it is trying to make installing Emacs easier. For me, installing Emacs was downloading a zipball, unpacking it into Program Files, running addpm.exe and copying and pasting a bunch of janky stuff off the wiki to try to set up shortcuts and file associations and the like.  This automates checking for updates, downloading and unpacking the zipball, and subsumes parts of what addpm.exe does. It was going to manage file types as well, but Microsoft basically made it so you can't do that anymore. C'est la vie.

The second is that it has functionality for running Emacs as a daemon.

More Unix jargon and a brief sidebar: "daemon" is Linux for "background service" and has to do with programs that your system is running even when you're logged out. Windows has services - I opened up my service explorer and saw a lot of update-checking agents and some whacky stuff from Origin (EA's game launcher) - but on Linux this is often stuff like web servers and ssh services.

So Emacs supports being ran headless, ie "as a daemon". In this mode, you run a headless Emacs and you open your files by connecting to the daemon with `emacsclientw.exe` instead of running `runemacs.exe` directly. In Windows, this connects to the headless Emacs over TCP. The primary advantage of this is that when you close all your Emacs windows, Emacs itself is still open in the background.

Like I mention in the documentation, Emacs can take a long time to load depending on how your config is set up. Vanilla Doom is pretty fast because it's pretty lightweight and obsessively performance-tuned, but [spacemacs](https://www.spacemacs.org/) with all the bells and whistles can take a good 20 seconds to go from zero to ready. In addition - and I don't explain this well - using a single server means multiple client windows can share state. Using a daemon means that you have one persistent Emacs that runs through your entire session, no matter how many windows you open and close.

Running Emacs in client/server mode (ie "as a daemon") is *entirely optional*. I didn't run Emacs in client/server mode while developing this because I didn't have the tools to do so yet :) and many people will get along just fine without it.

If you do decide to run Emacs as a daemon though, CD has functionality that will help you stop start and restart the thing running in the background, as well as a thing that collects logs from it. You may have noticed that if you run 'emacs.exe' in a PowerShell window that it prints some stuff to the screen - it's a small thing, but I collect that.

The third major thing that I do is that I made a little icon in the bottom corner that exposes buttons for hooking onto the daemon management stuff. So if you want to run Emacs as a daemon, the little widget will automatically start it and give you a few buttons for interacting with it, and from there the only real change you have to make to your workflow is using `emacsclientw.exe` instead of `runemacs.exe`, with the caveat that Doom requires some special setup - there's a note about this [here](https://github.com/jfhbrook/Cackledaemon/blob/master/Cackledaemon.org#tcp-server-file).

As far as Doom specifically goes, I punted on that entirely. I know the name is related to the video game, but like I said it's mostly coincidental. It works fine alongside Doom - I use Doom myself and [there's a feature I wrote specifically with Doom in mind](https://github.com/jfhbrook/Cackledaemon/blob/master/Cackledaemon.org#post-install-hooks) - but a lot of Emacs users use Spacemacs, or run vanilla, or write their own config. It's hard to meet everyone's use cases. But also, I needed to draw the line at scope somewhere. :)

On a really practical level:

* If you wanted to use Cackledaemon, you could say, OK don't think about this too hard but run this script and then use `emacsclientw.exe` to open everything, though it's [definitely beta quality software](https://github.com/jfhbrook/Cackledaemon/issues/6) and you might want to wait until the kinks are worked out before you recommend it to people.
* If you didn't want to deal with the added overhead of thinking about clients and servers and yadda yadda - Cackledaemon doesn't have great support for this right now and maybe never will, but you might still find some of the notes I took useful in terms of getting a runbook together for handing people to get their own installs working.
* If your major sticking point isn't Emacs itself but is more getting Doom to build in the first place, I can earnestly recommend trying Spacemacs. It's not as fast as Doom but it's a significantly lower lift to get working on Windows.

I hope this is helpful. I didn't really do a good job at making the explanations on the blog or the literate program approachable for non-hackers and honestly could have done a better job there. Maybe this will turn into a follow-up blog post, who knows.

**Comment by jfhbrook** [comment]
Oh, and to answer your last question - and I should add this to the documentation - but if you already have Emacs installed, you can edit `AppData/Roaming/Cackledaemon/Configuration.ps1` and update the directory that it thinks Emacs is installed in to point to the right one, and it'll do the right thing from there.

**Comment by quickfold** [comment]
Thanks for the full explanation. I do want to install and run Emacs using Cackledaemon, so hope it's ok to follow-up more with some numbered questions, and I apologize in advance for the length. BTW, I can help you with documentation later if you like.

> If you do decide to run Emacs as a daemon though, CD has functionality that will help you stop start and restart the thing running in the background, as well as a thing that collects logs from it. You may have noticed that if you run 'emacs.exe' in a PowerShell window that it prints some stuff to the screen - it's a small thing, but I collect that.

That is useful for me - it would help me debug problems.

> The third major thing that I do is that I made a little icon in the bottom corner that exposes buttons for hooking onto the daemon management stuff. So if you want to run Emacs as a daemon, the little widget will automatically start it and give you a few buttons for interacting with it, and from there the only real change you have to make to your workflow is using emacsclientw.exe instead of runemacs.exe, with the caveat that Doom requires some special setup - there's a note about this here.

1. So to check my understanding: if I have a shortcut to Emacs on my desktop, I should link it to C`:\path\to\emacs\emacsclientw.exe` instead of `runmacs.exe`. Are there any flags you recommend adding? For example, based on instructions I found elsewhere, I have my current shortcut as: `C:\Emacs\bin\emacsclientw.exe --alternate-editor="C:\Emacs\bin\runemacs.exe" -c`.

2. You say that Doom Emacs requires special setup, namely setting the `EMACS_SERVER_FILE` environmental variable. I did follow the instructions [here](https://github.com/earvingad/configfiles/blob/master/emacs/DoomEmacsWindows.org) to set up Doom Emacs. If I want to set the variable you note, how do I do that in Windows? Or do the instructions I linked to already take care of this?

> As far as Doom specifically goes, I punted on that entirely. I know the name is related to the video game, but like I said it's mostly coincidental. It works fine alongside Doom - I use Doom myself and there's a feature I wrote specifically with Doom in mind - but a lot of Emacs users use Spacemacs, or run vanilla, or write their own config. It's hard to meet everyone's use cases. But also, I needed to draw the line at scope somewhere. :)

It's totally fine that you want a distribution-agnostic approach, I am just trying to get my setup working so I can write instructions for Doom Emacs for others.

3. You write "For example, if you’re using Doom Emacs, you might add this to your Configuration.ps1: `$PostInstallHook = { doom build }`". So if I write install instructions for Doom Emacs specifically, I need to have people add this to Configuration.ps1, correct? Or is it just an option? 

Actually, a neat addition at some point (low priority) would be setting up options for automatically having Doom sync/update/upgrade on each daemon launch or daily.

> On a really practical level: If you wanted to use Cackledaemon, you could say, OK don't think about this too hard but run this script and then use emacsclientw.exe to open everything, though it's definitely beta quality software and you might want to wait until the kinks are worked out before you recommend it to people.

So I think that my eventual workflow doc will actually be fairly widely shared, hopefully in about a month. I'll check first but I suspect that you will have things mostly worked out by then.

> If you didn't want to deal with the added overhead of thinking about clients and servers and yadda yadda - Cackledaemon doesn't have great support for this right now and maybe never will, but you might still find some of the notes I took useful in terms of getting a runbook together for handing people to get their own installs working.

The end goal is just Emacs on one machine with one user - nothing more complicated.

> If your major sticking point isn't Emacs itself but is more getting Doom to build in the first place, I can earnestly recommend trying Spacemacs. It's not as fast as Doom but it's a significantly lower lift to get working on Windows.

I have committed to Doom Emacs over Spacemacs, in part because the dev Henrik is available 12 hours a day on Discord and provides an insane level of real-time support. I would have never gotten it set up without him. And I already am 75% done with clear install documentation.

> I hope this is helpful. I didn't really do a good job at making the explanations on the blog or the literate program approachable for non-hackers and honestly could have done a better job there. Maybe this will turn into a follow-up blog post, who knows.

You have no obligation to write for new-to-Emacs users, so don't feel bad at all. I genuinely appreciate the time you spent responding to me.

> Oh, and to answer your last question - and I should add this to the documentation - but if you already have Emacs installed, you can edit AppData/Roaming/Cackledaemon/Configuration.ps1 and update the directory that it thinks Emacs is installed in to point to the right one, and it'll do the right thing from there.

4. Just to check, you are saying that if I edit Configuration.ps1, then I don't need to uninstall my current setup for Cackledaemon to work?

5. Re updates, if I 'update' Cackledaemon through the Tray interface, and independently update Doom through Powershell/Command Prompt, that should not cause any conflicts, right? I think the answer is "obviously, that's no problem" but since it was not explicit I just want to double check with you.

6. Lastly, do you know: Am I correct that running Emacs as a daemon will allow me to assign Emacs as a default program in Win for e.g. .org files and have them open in the current running instance of Emacs?

Thank you again!

**Comment by jfhbrook** [comment]
> So to check my understanding: if I have a shortcut to Emacs on my desktop, I should link it to C:\path\to\emacs\emacsclientw.exe instead of runmacs.exe. Are there any flags you recommend adding? For example, based on instructions I found elsewhere, I have my current shortcut as: C:\Emacs\bin\emacsclientw.exe --alternate-editor="C:\Emacs\bin\runemacs.exe" -c.

That's right. Those flags look right - with that setting, if the daemon is down it'll run non-daemon emacs, and -c will make it open in a new window.

> You say that Doom Emacs requires special setup, namely setting the EMACS_SERVER_FILE environmental variable. I did follow the instructions here to set up Doom Emacs. If I want to set the variable you note, how do I do that in Windows? Or do the instructions I linked to already take care of this?

If you type "environment variables" into the search bar it'll pop up a thing you can go to, and that'll have a "change environment variables" button. I did some quick googling - I'm on my mac - and https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0 these look right.

> You write "For example, if you’re using Doom Emacs, you might add this to your Configuration.ps1: $PostInstallHook = { doom build }". So if I write install instructions for Doom Emacs specifically, I need to have people add this to Configuration.ps1, correct? Or is it just an option?

I think you should add this to the instructions, yeah - if you don't then doom might not start properly.

Agree that adding other hooks and/or special support for common configs like doom is a good idea. I'll make an issue for it, which means it might happen someday. :)

> Just to check, you are saying that if I edit Configuration.ps1, then I don't need to uninstall my current setup for Cackledaemon to work?

That's correct!

> Re updates, if I 'update' Cackledaemon through the Tray interface, and independently update Doom through Powershell/Command Prompt, that should not cause any conflicts, right? I think the answer is "obviously, that's no problem" but since it was not explicit I just want to double check with you.

Yes, this should work fine.

> Lastly, do you know: Am I correct that running Emacs as a daemon will allow me to assign Emacs as a default program in Win for e.g. .org files and have them open in the current running instance of Emacs?

Yup, if you tell explorer to use emacsclient to open .org files they should be opened using the daemon. Unfortunately setting CLI params can be a challenge here, I think you'll have to make a wrapper .bat file to get them all working, but this is how I have it set up and it works well enough.

**Comment by quickfold** [comment]
Thanks! I'm still a bit confused on when I make the config changes, since the install Powershell code you provide: 

`Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/jfhbrook/Cackledaemon/master/InstallWizard.ps1')`

...seems to download and install everything, but I can't edit the config before I run that code to download Configuration.ps1, right? So:

1. You talked about editing Configuration.ps1 - but that is only installed after Cackledaemon is installed, right? So I should run the provided snippet, and *then* edit configuration.ps1?

2. There are some warnings about installing over a current Emacs install creating problems. Is that just `buyer beware` stuff or should I worry about it? I promise I won't hold you responsible if things get messed up, just what's your suggestion?

3. Where in Configuration.ps1 do I add the line `$PostInstallHook = { doom build }`?

**Comment by jfhbrook** [comment]
Yeah, the workflow here isn't great. The move would be to install CD (so say yes to the first step), then say no to installing emacs; then open ~/AppData/Roaming/Cackledaemon/Configuration.ps1 and edit, then run `Invoke-CDInstallWizard` to run the wizard again with the updated config.

**Comment by quickfold** [comment]
- Does it matter where in `Configuration.ps1` I put the line `$PostInstallHook = { doom build }`?
- When I ran `Invoke-CDInstallWizard` I got this error:
```
Do you want to install a managed Emacs alongside the version of Emacs already installed?
Whaddaya think?
[Y] Yes  [N] No  [?] Help (default is "N"): y
Installing Emacs...
New-Object : Exception calling ".ctor" with "3" argument(s): "End of Central Directory record could not be found."
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:934
char:23
+ ... ipArchive = New-Object -TypeName System.IO.Compression.ZipArchive -Ar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

Invoke-AsAdministrator : C:\Program Files\emacs\bin\emacs.exe doesn't exist - refusing to write this to the registry.
At C:\Users\Username\Documents\WindowsPowerShell\Modules\Cackledaemon\0.1.7\Cackledaemon.psm1:859 char:5
+     Invoke-AsAdministrator "
+     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\emacs\bin\emacs.exe:String) [Write-CDError], Exception
    + FullyQualifiedErrorId : ItemNotFoundException,Write-CDError

PS C:\Users\Username\AppData\Roaming\Cackledaemon>
```

**Comment by jfhbrook** [comment]
As to your question? No, the order shouldn't matter.

As to that stack trace: Wow, that's intense. My guess is that the archive is busted - can you manually remove ~/AppData/Roaming/Cackledaemon/Workspace/Archives/*.zip and try again?

If that doesn't work: this one might need some more hands-on attention. I'd be open to screen sharing - have you used discord before? There are other options but I like Discord's best.

**Comment by jfhbrook** [comment]
I *think* removing the zip will do it - if that's the case then I need to write a patch that catches this error, removes the archive and tries again.

**Comment by quickfold** [comment]
Just FYI, I now have Cackledaemon installed and working! One other small suggestion: have an option (or default) so that when the user clicks on the Cackledaemon shortcut, an Emacs window automatically opens as well. Presumably, there would be very few times you would not want to do it anyway, and it saves another menu interaction to find/click `Emacs`. Oh, and maybe also add an Emacs shortcut to the Cackledaemon tray icon menu. Thanks for your help!

**Comment by jfhbrook** [comment]
Glad you were able to get on your way! :+1:
